### ISSUE TITLE
Remove plotJuggler install

### ISSUE THREAD

**Issue by lukaszmitka** [byq77/husarion-docs-dev#2]
Ros image should contain all packages needed for tutorials. If new one is required, we can add them in next release. 
Lines:
sudo apt-get update
sudo apt-get install ros-kinetic-plotjuggler 
should be removed.

**Comment by byq77** [comment]
Fixed in https://github.com/byq77/husarion-docs-dev/commit/f5ff82e726231b0b3015c9fb5c8df00ec625a443
