### ISSUE TITLE
Add link to implementation

### ISSUE THREAD

**Issue by lukaszmitka** [byq77/husarion-docs-dev#3]
In section Forward Kinematics task, a link to implementation of equations could make some things clearer:
https://github.com/husarion/hFramework/blob/master/src/rosbot/ROSbot.cpp#L126

**Comment by byq77** [comment]
Fixed in https://github.com/byq77/husarion-docs-dev/commit/f5ff82e726231b0b3015c9fb5c8df00ec625a443
